DROP TABLE racing.dbo.tracks
select * into racing.dbo.TRACKS FROM racingrestore.dbo.tracks
DROP TABLE racing.dbo.races
select * into racing.dbo.RACES FROM racingrestore.dbo.RACES
DROP TABLE racing.dbo.MEETS
select * into racing.dbo.MEETS FROM racingrestore.dbo.MEETS
DROP TABLE racing.dbo.DOGS
select * into racing.dbo.DOGS FROM racingrestore.dbo.DOGS
DROP TABLE racing.dbo.NETWORKRESULTS
select * into racing.dbo.NETWORKRESULTS FROM racingrestore.dbo.NETWORKRESULTS
DROP TABLE racing.dbo.NETWORKDETAILS
select * into racing.dbo.NETWORKDETAILS FROM racingrestore.dbo.NETWORKDETAILS
update racing.dbo.NETWORKDETAILS SET nnfilename = REPLACE(nnfilename, 'Testing', 'FinalVersions')
DROP TABLE racing.dbo.RESULTS
select * into racing.dbo.RESULTS FROM racingrestore.dbo.RESULTS
DROP TABLE racing.dbo.FEATURES_DETAIL
select * into racing.dbo.FEATURES_DETAIL FROM racingrestore.dbo.FEATURES_DETAIL





/****** Object:  Index [INDEX2]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE CLUSTERED INDEX [INDEX2] ON [dbo].[TRAININGDATA]
(
	[D_P_M] ASC,
	[DOGID] ASC,
	[RACEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [INDEX1]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX1] ON [dbo].[DOGS]
(
	[DOGNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [NonClusteredIndex-20140924-084308]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20140924-084308] ON [dbo].[FEATURES_DETAIL]
(
	[NNID] ASC,
	[FEATURE] ASC,
	[DESCRIPTION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [INDEX1]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX1] ON [dbo].[PREDICTEDRESULTS]
(
	[nnid] ASC,
	[RACEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [INDEX1]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX1] ON [dbo].[PREDICTEDRESULTS_old]
(
	[nnid] ASC,
	[RACEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [INDEX1]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX1] ON [dbo].[RACES]
(
	[MEETID] ASC,
	[RACENUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [INDEX2]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX2] ON [dbo].[RACES]
(
	[STARTTIME] ASC
)
INCLUDE ( 	[RACEID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [INDEX3]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX3] ON [dbo].[RACES]
(
	[STARTTIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [INDEX4]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX4] ON [dbo].[RACES]
(
	[TRACKID] ASC
)
INCLUDE ( 	[RACEID],
	[STARTTIME],
	[WINPAYING],
	[PLACEPAYING],
	[QUINELLAPAYING],
	[TRIFECTAPAYING],
	[FIRST4PAYING]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [INDEX5]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX5] ON [dbo].[RACES]
(
	[RACEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [INDEX1]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX1] ON [dbo].[RESULTS]
(
	[RACEID] ASC,
	[TRACKID] ASC,
	[DOGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [INDEX1]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX1] ON [dbo].[TEMP_RACEDATA]
(
	[DOGID] ASC,
	[RESULT] ASC,
	[RACEID] ASC,
	[STARTTIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [INDEX2]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX2] ON [dbo].[TEMP_RACEDATA]
(
	[RACEID] ASC,
	[DOGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [INDEX]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX] ON [dbo].[TRAININGDATA]
(
	[RACEID] ASC,
	[DOGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [INDEX1]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX1] ON [dbo].[TRAININGDATA]
(
	[DATATYPE] ASC
)
INCLUDE ( 	[RACEID],
	[DOGID],
	[D_1_M],
	[D_2_M],
	[D_3_M],
	[D_1_6M],
	[D_2_6M],
	[D_3_6M],
	[D_1D_A],
	[D_2D_A],
	[D_3D_A],
	[D_P_M],
	[D_PB_A],
	[D_PWC_A],
	[D_1MBREAK],
	[RESULT],
	[D_1_M1],
	[D_2_M1],
	[D_3_M1],
	[D_1D_A1],
	[D_2D_A1],
	[D_3D_A1],
	[D_P_A1],
	[D_P_M1],
	[D_PT_A1],
	[D_PB_A1],
	[D_PWC_A1],
	[D_PTC_A1],
	[D_1_M2],
	[D_2_M2],
	[D_3_M2],
	[D_1D_A2],
	[D_2D_A2],
	[D_3D_A2],
	[D_P_A2],
	[D_P_M2],
	[D_PT_A2],
	[D_PB_A2],
	[D_PWC_A2],
	[D_PTC_A2],
	[D_1_M3],
	[D_2_M3],
	[D_3_M3],
	[D_1D_A3],
	[D_2D_A3],
	[D_3D_A3],
	[D_P_A3],
	[D_P_M3],
	[D_PT_A3],
	[D_PB_A3],
	[D_PWC_A3],
	[D_PTC_A3]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [INDEX3]    Script Date: 25/09/2014 4:49:23 p.m. ******/
CREATE NONCLUSTERED INDEX [INDEX3] ON [dbo].[TRAININGDATA]
(
	[D_1_M] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

